from .database import SessionLocal, engine, Base
from .models import (
    User,
    Course,
    Topic,
    Question,
    TrainerTopic,
    TrainerSlot,
)


def get_or_create_course(db, title, description):
    course = db.query(Course).filter(Course.title == title).first()

    if not course:
        course = Course(
            title=title,
            description=description
        )
        db.add(course)
        db.commit()
        db.refresh(course)

    return course


def get_or_create_topic(db, course_id, name):
    topic = (
        db.query(Topic)
        .filter(
            Topic.course_id == course_id,
            Topic.name == name
        )
        .first()
    )

    if not topic:
        topic = Topic(
            course_id=course_id,
            name=name
        )
        db.add(topic)
        db.commit()
        db.refresh(topic)

    return topic


def add_question(
    db,
    course_id,
    topic_id,
    text,
    option_a,
    option_b,
    option_c,
    option_d,
    correct_answer
):
    existing = (
        db.query(Question)
        .filter(
            Question.course_id == course_id,
            Question.topic_id == topic_id,
            Question.text == text
        )
        .first()
    )

    if existing:
        return existing

    question = Question(
        course_id=course_id,
        topic_id=topic_id,
        text=text,
        option_a=option_a,
        option_b=option_b,
        option_c=option_c,
        option_d=option_d,
        correct_answer=correct_answer
    )

    db.add(question)
    db.commit()
    db.refresh(question)

    return question


def get_or_create_trainer(db, name, email, bio):
    trainer = (
        db.query(User)
        .filter(User.email == email)
        .first()
    )

    if not trainer:
        trainer = User(
            name=name,
            email=email,
            password="Demo@123",
            role="trainer",
            bio=bio
        )

        db.add(trainer)
        db.commit()
        db.refresh(trainer)

    return trainer


def add_trainer_topic(db, trainer_id, topic_id):
    existing = (
        db.query(TrainerTopic)
        .filter(
            TrainerTopic.trainer_id == trainer_id,
            TrainerTopic.topic_id == topic_id
        )
        .first()
    )

    if not existing:
        db.add(
            TrainerTopic(
                trainer_id=trainer_id,
                topic_id=topic_id
            )
        )
        db.commit()


def add_slot(db, trainer_id, start_time, end_time):
    existing = (
        db.query(TrainerSlot)
        .filter(
            TrainerSlot.trainer_id == trainer_id,
            TrainerSlot.start_time == start_time,
            TrainerSlot.end_time == end_time
        )
        .first()
    )

    if not existing:
        db.add(
            TrainerSlot(
                trainer_id=trainer_id,
                start_time=start_time,
                end_time=end_time,
                available=True
            )
        )
        db.commit()


def seed_python(db):
    course = get_or_create_course(
        db,
        "Python",
        "Learn Python programming from basics to object oriented programming."
    )

    topics = {}

    topic_names = [
        "Python Basics",
        "Variables & Data Types",
        "Control Flow",
        "Functions",
        "OOP in Python"
    ]

    for name in topic_names:
        topics[name] = get_or_create_topic(
            db,
            course.id,
            name
        )

    questions = [
        (
            "Python file usually has which extension?",
            ".py", ".java", ".cpp", ".html", "A"
        ),
        (
            "Which function is used to display output in Python?",
            "input()", "print()", "display()", "show()", "B"
        ),
        (
            "Python is mainly a ______ language.",
            "Interpreted", "Assembly", "Machine", "Binary", "A"
        ),

        (
            "What is the type of 10 in Python?",
            "float", "str", "int", "bool", "C"
        ),
        (
            "Which data type is immutable?",
            "list", "tuple", "set", "dictionary", "B"
        ),
        (
            "What is the result type of 10 / 2?",
            "int", "float", "str", "bool", "B"
        ),

        (
            "Which keyword is used for a condition?",
            "for", "while", "if", "def", "C"
        ),
        (
            "What values are generated by range(3)?",
            "1,2,3", "0,1,2", "0,1,2,3", "3,2,1", "B"
        ),
        (
            "Which keyword immediately exits a loop?",
            "skip", "continue", "exit", "break", "D"
        ),

        (
            "Which keyword defines a function?",
            "function", "func", "def", "define", "C"
        ),
        (
            "Which keyword sends a value back from a function?",
            "send", "return", "back", "value", "B"
        ),
        (
            "What is a default parameter?",
            "A parameter with a predefined value",
            "A global variable",
            "A class",
            "A loop",
            "A"
        ),

        (
            "A class is commonly considered a ______ for objects.",
            "loop", "blueprint", "function", "variable", "B"
        ),
        (
            "Which method commonly initializes an object?",
            "__start__", "__main__", "__init__", "__newobject__", "C"
        ),
        (
            "Inheritance allows a class to ______ properties of another class.",
            "delete", "reuse", "hide", "remove", "B"
        ),
    ]

    topic_list = topic_names

    for i, q in enumerate(questions):
        topic = topics[topic_list[i // 3]]

        add_question(
            db,
            course.id,
            topic.id,
            q[0],
            q[1],
            q[2],
            q[3],
            q[4],
            q[5]
        )

    return course, topics


def seed_cyber(db):
    course = get_or_create_course(
        db,
        "Cyber Security",
        "Learn the fundamentals of cyber security, networks and web security."
    )

    topic_names = [
        "Security Basics",
        "Network Security",
        "Cryptography",
        "Web Security",
        "Ethical Hacking"
    ]

    topics = {}

    for name in topic_names:
        topics[name] = get_or_create_topic(
            db,
            course.id,
            name
        )

    questions = [
        (
            "What does CIA stand for in cyber security?",
            "Confidentiality, Integrity, Availability",
            "Control, Internet, Access",
            "Cyber, Information, Authentication",
            "Computer, Integrity, Access",
            "A"
        ),
        (
            "Which is an example of social engineering?",
            "Phishing", "Encryption", "Firewall", "Backup", "A"
        ),
        (
            "Malware is software designed to ______.",
            "Protect data",
            "Damage or exploit systems",
            "Create backups",
            "Improve speed",
            "B"
        ),

        (
            "What is the main purpose of a firewall?",
            "Filter network traffic",
            "Create passwords",
            "Store files",
            "Compile code",
            "A"
        ),
        (
            "HTTPS mainly provides ______.",
            "Encrypted communication",
            "Faster CPU",
            "File compression",
            "Database indexing",
            "A"
        ),
        (
            "VPN is mainly used to create a ______ connection.",
            "Private and encrypted",
            "Public",
            "Unstable",
            "Offline",
            "A"
        ),

        (
            "Encryption converts plaintext into ______.",
            "Source code", "Ciphertext", "HTML", "Database", "B"
        ),
        (
            "Which cryptography uses the same key for encryption and decryption?",
            "Symmetric", "Asymmetric", "Hashing", "None", "A"
        ),
        (
            "A cryptographic hash is generally designed to be ______.",
            "Reversible", "One-way", "Editable", "Readable", "B"
        ),

        (
            "SQL Injection targets ______.",
            "Databases",
            "Monitors",
            "Printers",
            "Keyboards",
            "A"
        ),
        (
            "XSS stands for ______.",
            "Cross-Site Scripting",
            "Extra Secure System",
            "Cross Server Security",
            "External Script Service",
            "A"
        ),
        (
            "CSRF attacks mainly abuse a user's ______.",
            "Authenticated session",
            "Hard disk",
            "CPU",
            "Keyboard",
            "A"
        ),

        (
            "Ethical hacking requires ______.",
            "Authorization",
            "Secret access",
            "No permission",
            "Password stealing",
            "A"
        ),
        (
            "Penetration testing is used to find ______.",
            "Security weaknesses",
            "Music files",
            "Printer errors",
            "Screen resolution",
            "A"
        ),
        (
            "Reconnaissance is generally the ______ phase.",
            "Information gathering",
            "Deletion",
            "Recovery",
            "Shutdown",
            "A"
        ),
    ]

    for i, q in enumerate(questions):
        topic = topics[topic_names[i // 3]]

        add_question(
            db,
            course.id,
            topic.id,
            q[0],
            q[1],
            q[2],
            q[3],
            q[4],
            q[5]
        )

    return course, topics


def seed_database_course(db):
    course = get_or_create_course(
        db,
        "Database",
        "Learn DBMS, SQL, normalization, transactions and indexing."
    )

    topic_names = [
        "DBMS Basics",
        "SQL",
        "Normalization",
        "Transactions",
        "Indexing"
    ]

    topics = {}

    for name in topic_names:
        topics[name] = get_or_create_topic(
            db,
            course.id,
            name
        )

    questions = [
        (
            "What is a database?",
            "Collection of organized data",
            "Operating system",
            "Compiler",
            "Network cable",
            "A"
        ),
        (
            "DBMS stands for ______.",
            "Database Management System",
            "Data Backup Management System",
            "Database Machine System",
            "Digital Base Management Service",
            "A"
        ),
        (
            "A primary key should uniquely identify a ______.",
            "Record", "Database server", "Table only", "Program", "A"
        ),

        (
            "Which SQL command retrieves data?",
            "SELECT", "INSERT", "DELETE", "UPDATE", "A"
        ),
        (
            "Which command adds a new record?",
            "SELECT", "INSERT", "DROP", "ALTER", "B"
        ),
        (
            "Which clause filters rows?",
            "ORDER BY", "GROUP BY", "WHERE", "FROM", "C"
        ),

        (
            "1NF requires values to be ______.",
            "Atomic", "Encrypted", "Duplicated", "Sorted", "A"
        ),
        (
            "2NF mainly removes ______ dependency.",
            "Partial", "Network", "Circular", "External", "A"
        ),
        (
            "3NF mainly removes ______ dependency.",
            "Transitive", "Primary", "Network", "Physical", "A"
        ),

        (
            "Which property of ACID means all-or-nothing?",
            "Atomicity", "Consistency", "Isolation", "Durability", "A"
        ),
        (
            "Which command permanently saves a transaction?",
            "SAVE", "COMMIT", "STORE", "PUSH", "B"
        ),
        (
            "Which command cancels transaction changes?",
            "UNDO", "CANCEL", "ROLLBACK", "DELETE", "C"
        ),

        (
            "An index is mainly used to improve ______.",
            "Query/search speed",
            "Screen resolution",
            "Password strength",
            "CPU temperature",
            "A"
        ),
        (
            "Which structure is commonly used for database indexes?",
            "B-tree", "Stack", "Queue", "Linked list only", "A"
        ),
        (
            "Too many indexes can negatively affect ______.",
            "Write performance",
            "Monitor brightness",
            "Internet speed",
            "Keyboard input",
            "A"
        ),
    ]

    for i, q in enumerate(questions):
        topic = topics[topic_names[i // 3]]

        add_question(
            db,
            course.id,
            topic.id,
            q[0],
            q[1],
            q[2],
            q[3],
            q[4],
            q[5]
        )

    return course, topics


def seed_trainers(db, python_topics, cyber_topics, database_topics):

    trainers = {}

    trainers["Rahul"] = get_or_create_trainer(
        db,
        "Rahul Sharma",
        "rahul.trainer@skillsphere.com",
        "Python Programming Trainer"
    )

    trainers["Amit"] = get_or_create_trainer(
        db,
        "Amit Verma",
        "amit.trainer@skillsphere.com",
        "Cyber Security Trainer"
    )

    trainers["Neha"] = get_or_create_trainer(
        db,
        "Neha Gupta",
        "neha.trainer@skillsphere.com",
        "Database Trainer"
    )

    trainers["Arjun"] = get_or_create_trainer(
        db,
        "Arjun Kumar",
        "arjun.trainer@skillsphere.com",
        "Python and Cyber Security Trainer"
    )

    trainers["Rohit"] = get_or_create_trainer(
        db,
        "Rohit Mehta",
        "rohit.trainer@skillsphere.com",
        "Database and Python Trainer"
    )

    # Rahul → Python
    for topic in python_topics.values():
        add_trainer_topic(
            db,
            trainers["Rahul"].id,
            topic.id
        )

    # Amit → Cyber Security
    for topic in cyber_topics.values():
        add_trainer_topic(
            db,
            trainers["Amit"].id,
            topic.id
        )

    # Neha → Database
    for topic in database_topics.values():
        add_trainer_topic(
            db,
            trainers["Neha"].id,
            topic.id
        )

    # Arjun → selected Python + Cyber topics
    for name in [
        "Control Flow",
        "Functions"
    ]:
        add_trainer_topic(
            db,
            trainers["Arjun"].id,
            python_topics[name].id
        )

    for name in [
        "Network Security",
        "Web Security"
    ]:
        add_trainer_topic(
            db,
            trainers["Arjun"].id,
            cyber_topics[name].id
        )

    # Rohit → selected Database + Python topics
    for name in [
        "SQL",
        "Normalization",
        "Indexing"
    ]:
        add_trainer_topic(
            db,
            trainers["Rohit"].id,
            database_topics[name].id
        )

    add_trainer_topic(
        db,
        trainers["Rohit"].id,
        python_topics["Python Basics"].id
    )

    # Demo slots
    add_slot(db, trainers["Rahul"].id, "10:00 AM", "11:00 AM")
    add_slot(db, trainers["Rahul"].id, "04:00 PM", "05:00 PM")

    add_slot(db, trainers["Amit"].id, "11:00 AM", "12:00 PM")
    add_slot(db, trainers["Amit"].id, "06:00 PM", "07:00 PM")

    add_slot(db, trainers["Neha"].id, "12:00 PM", "01:00 PM")
    add_slot(db, trainers["Neha"].id, "05:00 PM", "06:00 PM")

    add_slot(db, trainers["Arjun"].id, "02:00 PM", "03:00 PM")
    add_slot(db, trainers["Arjun"].id, "07:00 PM", "08:00 PM")

    add_slot(db, trainers["Rohit"].id, "03:00 PM", "04:00 PM")
    add_slot(db, trainers["Rohit"].id, "08:00 PM", "09:00 PM")


def seed_database():

    db = SessionLocal()

    try:
        python_course, python_topics = seed_python(db)

        cyber_course, cyber_topics = seed_cyber(db)

        database_course, database_topics = seed_database_course(db)

        seed_trainers(
            db,
            python_topics,
            cyber_topics,
            database_topics
        )

        print("====================================")
        print("SkillSphere database seeded successfully")
        print("Courses: Python, Cyber Security, Database")
        print("Demo trainers added")
        print("====================================")

    finally:
        db.close()


if __name__ == "__main__":
    Base.metadata.create_all(bind=engine)
    seed_database()
